version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-tier

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  web:
    build:
      context: .
    ports:
      - 5000:5000
      - 443:443
    volumes:
      - ./:/app
    networks:
      - app-tier
